# Generated by Django 4.1.7 on 2023-03-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0003_rename_max_palyer_turf_max_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price_per_hour', models.IntegerField()),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turftime', to='turfs.turf')),
            ],
        ),
    ]
