# Generated by Django 4.1.7 on 2023-03-10 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turfs', '0005_alter_turf_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked_Timeslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='turfs.timeslots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookinguser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
