# Generated by Django 4.1.7 on 2023-03-18 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_timeslots',
            name='turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turfbooking', to='turfs.turf'),
        ),
    ]
